version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  secrets-manager:
    OAUTH_TOKEN: " git_oauth_token:oauth_token"

phases:
  install:
    commands:  # Install AWS cli, kubectl (needed for Helm) and Helm
      - apt-get update
      - apt install -y awscli git python3
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

  pre_build:
    commands:
      - AWS_ACCOUNT_ID=705303224111
      - AWS_DEFAULT_REGION=eu-west-1
      - IMAGE_REPO_NAME=typegenie-api-client
      - ENV=staging
      - aws --version
      - GITHUB_USER=renatomrochatg
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - REPOSITORY_URI=$ECR_URI/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t deployment-container:latest -f Production.Dockerfile .
      - docker build -t tester-container:latest -f Tests.Dockerfile .
      - echo Running tests from test container

  post_build:
    commands:
      - echo Build completed on `date`
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" == 1 ]; then
          docker run -v $(pwd):/root/TypeGenieJSClient deployment-container:latest git remote set-url origin https://$GITHUB_USER:$OAUTH_TOKEN@github.com/abhitopia/TypeGenieJSClient.git
          docker run -v $(pwd):/root/TypeGenieJSClient deployment-container:latest git fetch
          docker run -v $(pwd):/root/TypeGenieJSClient deployment-container:latest git checkout production
          docker run -v $(pwd):/root/TypeGenieJSClient deployment-container:latest git tag production-release-$IMAGE_TAG
          docker run -v $(pwd):/root/TypeGenieJSClient deployment-container:latest git push origin production
          echo Commit successfully tagged
        else
          echo Unit tests did not pass... not suitable for staging release
        fi
